### ISSUE TITLE
How to install without docker?

### ISSUE THREAD

**Issue by saddy001** [fauxpilot/fauxpilot#180]
How to install fauxpilot without docker?

**Comment by thakkarparth007** [comment]
That can be an easy process or a slightly painful one depending upon how much control you have over where you're installing. If you have root access and it's an Ubuntu-like system, it'll be easyish.

Basically you need to do the following:

1. Build triton server (their docs show how to do this).
2. Build the fastertransformer backend. Refer to @moyix 's docker file for how to build it. 
3. Modify the setup.sh and launch.sh scripts so that they work without docker
4. Profit.

Now, the difficulty comes from the fact that you've to install dependencies for Triton and faster transformer backends. If you have root access, this will be easy. Otherwise you've to get the dependencies and build them from source first. Then you'll have to modify the cmake files while building Triton and fastertransformer so that they find these dependencies. There'll also be some issues regarding versioning - you're dealing with 3 systems (Triton, fastertransformer backend, and faster transformer itself), and unfortunately I couldn't find clear guidelines on which versions are compatible with each other, so had to stumble my way through this.

I had to do this recently for a system where I didn't have root and not all libraries were installed. It was...an adventure. Wouldn't recommend unless you really have to do this.
